import type { Metadata } from "next";

import { CONTACT } from "@/lib/contact";
import { SITE_NAME, SITE_URL, absoluteUrl } from "@/lib/site";
import { routing, type Locale } from "@/i18n/routing";

/**
 * `alternates` block for a given locale + path. Always populates `canonical`
 * and the `languages` map (hreflang) so search engines correctly group the
 * three locale variants of each page.
 */
export function alternatesFor(locale: Locale, path: string): Metadata["alternates"] {
  const cleanPath = path === "/" ? "" : path;
  const canonical = `${SITE_URL}/${locale}${cleanPath}`;
  const languages = Object.fromEntries(
    routing.locales.map((l) => [l, `${SITE_URL}/${l}${cleanPath}`]),
  );
  // x-default points monolingual crawlers at the German page.
  languages["x-default"] = `${SITE_URL}/${routing.defaultLocale}${cleanPath}`;
  return { canonical, languages };
}

/**
 * Open Graph block, with a sensible default OG image (the dynamic one
 * generated by app/opengraph-image.tsx — Next picks it up automatically).
 */
export function openGraphFor({
  locale,
  path,
  title,
  description,
}: {
  locale: Locale;
  path: string;
  title: string;
  description: string;
}): Metadata["openGraph"] {
  const cleanPath = path === "/" ? "" : path;
  return {
    type: "website",
    siteName: SITE_NAME,
    locale: ogLocale(locale),
    alternateLocale: routing.locales.filter((l) => l !== locale).map(ogLocale),
    url: `${SITE_URL}/${locale}${cleanPath}`,
    title,
    description,
  };
}

export function twitterFor({
  title,
  description,
}: {
  title: string;
  description: string;
}): Metadata["twitter"] {
  return {
    card: "summary_large_image",
    title,
    description,
  };
}

function ogLocale(locale: Locale): string {
  if (locale === "de") return "de_DE";
  if (locale === "en") return "en_GB";
  if (locale === "lt") return "lt_LT";
  return "de_DE";
}

// ============ JSON-LD builders =================================================

export function personAndBusinessLD() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Person",
        "@id": `${SITE_URL}/#person`,
        name: SITE_NAME,
        jobTitle: [
          "Vereidigte Dolmetscherin Litauisch–Deutsch",
          "Registrierte Berufsbetreuerin",
        ],
        worksFor: { "@id": `${SITE_URL}/#localBusiness` },
        knowsLanguage: ["de", "lt", "en"],
        url: SITE_URL,
        telephone: CONTACT.phone,
        email: CONTACT.email,
        hasOccupation: [
          {
            "@type": "Occupation",
            name: "Sworn Court Interpreter Lithuanian–German",
            occupationLocation: { "@type": "State", name: CONTACT.region },
          },
          {
            "@type": "Occupation",
            name: "Professional Legal Guardian (BtOG)",
            occupationLocation: { "@type": "State", name: CONTACT.region },
          },
        ],
      },
      {
        "@type": "LocalBusiness",
        "@id": `${SITE_URL}/#localBusiness`,
        name: SITE_NAME,
        url: SITE_URL,
        telephone: CONTACT.phone,
        email: CONTACT.email,
        address: {
          "@type": "PostalAddress",
          addressLocality: CONTACT.city,
          addressRegion: CONTACT.region,
          addressCountry: CONTACT.country,
        },
        areaServed: [
          { "@type": "State", name: CONTACT.region },
          { "@type": "Country", name: CONTACT.country },
        ],
        founder: { "@id": `${SITE_URL}/#person` },
      },
    ],
  };
}

type Crumb = { name: string; path: string };

export function breadcrumbLD(locale: Locale, items: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, idx) => ({
      "@type": "ListItem",
      position: idx + 1,
      name: item.name,
      item: `${SITE_URL}/${locale}${item.path === "/" ? "" : item.path}`,
    })),
  };
}

export function faqPageLD(items: { q: string; a: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };
}

export function legalServiceLD(locale: Locale, name: string, description: string) {
  return {
    "@context": "https://schema.org",
    "@type": "LegalService",
    "@id": `${SITE_URL}/${locale}/dolmetschen#service`,
    name,
    description,
    provider: { "@id": `${SITE_URL}/#person` },
    areaServed: [
      { "@type": "State", name: CONTACT.region },
      { "@type": "Country", name: CONTACT.country },
    ],
    knowsLanguage: ["de", "lt"],
    hasCredential: "Allgemeine Beeidigung, Oberlandesgericht Düsseldorf",
    url: absoluteUrl(`/${locale}/dolmetschen`),
  };
}

export function professionalServiceLD(
  locale: Locale,
  name: string,
  description: string,
) {
  return {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    "@id": `${SITE_URL}/${locale}/rechtliche-betreuung#service`,
    name,
    description,
    serviceType: "Legal Guardianship",
    provider: { "@id": `${SITE_URL}/#person` },
    areaServed: [
      { "@type": "State", name: CONTACT.region },
      { "@type": "Country", name: CONTACT.country },
    ],
    knowsLanguage: ["de", "lt"],
    hasCredential: "Registrierte Berufsbetreuerin nach BtOG",
    url: absoluteUrl(`/${locale}/rechtliche-betreuung`),
  };
}

export function profilePageLD(locale: Locale, name: string, description: string) {
  return {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    name,
    description,
    mainEntity: { "@id": `${SITE_URL}/#person` },
    url: absoluteUrl(`/${locale}/ueber`),
  };
}

export function contactPageLD(locale: Locale, name: string, description: string) {
  return {
    "@context": "https://schema.org",
    "@type": "ContactPage",
    name,
    description,
    mainEntity: { "@id": `${SITE_URL}/#localBusiness` },
    url: absoluteUrl(`/${locale}/kontakt`),
  };
}
